version: '3'
services:
  are-you-bombed:
    build: .
    ports:
      - "${PORT}:${PORT}"
    command: sh -c "go run main.go generate flat 100 && go run main.go generate nested 10 && go run main.go host"
